server:
  port: 9090
spring:
  profiles:
    active: dev
    include: log

---
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /lee
  kafka:
    bootstrap-servers: localhost:9092
