# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot-example?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    druid:
      max-active: 20
      initial-size: 10
      max-wait: 60000
      min-idle: 10
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: cn.lee.example.entity
  global-config:
    db-config:
      #id-type: assign_id
      field-strategy: not_empty
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    # 启动mybatis本身的log日志,方式一
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 启动mybatis打印sql,方式二
#logging:
#  level:
#    cn.lee.example.mapper: debug